---
title: "team"
output: html_document
---

```{r}
library(ggplot2)
choco <- read.csv("https://xdaiisu.github.io/ds202materials/hwlabs/choco.csv")
dim(choco)

```

Given that the dimensions of this dataset are 1852 x 9, it is assumed that the number of chocolate bars tested is 1852.

#2
```{r}
year <- choco$Review.Date
ggplot(choco, aes(x = factor(year), y = Rating)) + geom_bar(stat= "identity")
```

#3 
```{r}
locations <- split(choco, choco$Company.Location)
usa <- locations$U.S.A.
france <- locations$France
canada <- locations$Canada

usaRatings <- usa$Rating
franceRatings <- france$Rating
canadaRatings <- canada$Rating

usaMean <- mean(usaRatings)
franceMean <- mean(franceRatings)
canadaMean <- mean(canadaRatings)
means <- c(canadaMean, franceMean, usaMean)

bar <- barplot(means, main="Average Rating by Country", names.arg=c("Canada", "France", "USA"), ylim = c(0, 4), ylab = "Avg Rating (out of 5.0)", col=c("lightblue", "mistyrose", "lavender"))
text(bar, 2.5, labels=format(round(means, digits=2)))
```

It appears that the ratings are fairly similar, although Canada does have the highest average rating, followed by France and then the USA.
```{r}
#4 what is the top10 rating count by bean origin?
```

```{r}
#5
count_rating <- as.data.frame(table(factor(choco$Rating), choco$Specific.Bean.Origin))
colnames(count_rating) <- c("Rating", "Bean_Orgin", "Freq")
count_rating[order(-count_rating$Freq, count_rating$Bean_Orgin),][1:10,]

```
